package de.mat2095.my_slither;

import javax.swing.*;
import java.awt.event.*;

final class Splash implements ActionListener {
 
    // private variables
    private JFrame splashFrame = new JFrame();
    private JPanel panel = new JPanel();

    /**
     * Class constructor
     */
    Splash() {

        // Add a button, to start with
        JButton startButton = new JButton("Start");
        panel.add(startButton);
        startButton.addActionListener(this);
        startButton.setName("start");

        // Create help button
        JButton helpButton = new JButton("Help");
        panel.add(helpButton);
        helpButton.addActionListener(this);
        helpButton.setName("help");

        // Configure the frame
        splashFrame.setContentPane(panel);
        splashFrame.setTitle("MySlither");
        splashFrame.setSize(300,300);
        splashFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        splashFrame.setVisible(true);
    }

    /**
     * Processes button presses in the GUI.
     * 
     * @param event the event generated by the button press
     */
    public void actionPerformed(ActionEvent event) {
        JButton source = (JButton) event.getSource();
        String name = (String) source.getName();

        // start the game if start button is pressed
        if name == "start" {
            // launch the game and close this current frame
            new MySlitherJFrame.setVisible(true);
            splashFrame.dispose();
        }

        if name == "help" {
            // launch the help window
            new Help();
        }


    }



}