package de.mat2095.my_slither;

import javax.swing.*;
import java.awt.event.*;

final class Splash implements ActionListener {
 
    // private variables
    private JFrame splashFrame = new JFrame();
    private JPanel panel = new JPanel();

    /**
     * Class constructor
     */
    Splash() {

        // Add a button, to start with
        JButton startButton = new JButton("Start");
        panel.add(startButton);
        startButton.addActionListener(this);
        startButton.setName("start");

        // Configure the frame
        splashFrame.setContentPane(panel);
        splashFrame.setTitle("MySlither");
        splashFrame.setSize(300,300);
        splashFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        splashFrame.setVisible(true);
    }

    /**
     * Processes button presses in the GUI.
     * 
     * @param event the event generated by the button press
     */
    public void actionPerformed(ActionEvent event) {
        JButton source = (JButton) event.getSource();
        String name = (String) source.getName();

        // for now, just launch game and close the frame on any button press.
        // this can be done properly later.
        new MySlitherJFrame().setVisible(true);
        splashFrame.dispose();


    }



}