package de.mat2095.my_slither;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.net.URL;

final class Splash implements ActionListener {
 
    // private variables
    private JFrame splashFrame = new JFrame();
    private JPanel panel = new JPanel();
    private JPanel buttonPanel = new JPanel();
    private GridBagLayout layout = new GridBagLayout();
    private FlowLayout buttonLayout = new FlowLayout();

    /**
     * Class constructor
     */
    Splash() {

        // Set layouts
        panel.setLayout(layout);
        buttonPanel.setLayout(buttonLayout);

        // Configure grid
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.gridx = 0;

        // Add a JLabel to explain app
        JLabel appTitle = new JLabel("<html><center><h1>MySlither</h1><h4>A Java-based Slither.io client.</h4></center></html>");
        constraints.gridy = 0;
        panel.add(appTitle, constraints);

        // Add a button, to start with
        JButton startButton = new JButton("Start");
        buttonPanel.add(startButton);
        startButton.addActionListener(this);
        startButton.setName("start");

        // Create help button
        JButton helpButton = new JButton("Help");
        buttonPanel.add(helpButton);
        helpButton.addActionListener(this);
        helpButton.setName("help");

        // Create exit button
        JButton exitButton = new JButton("Exit");
        buttonPanel.add(exitButton);
        exitButton.addActionListener(this);
        exitButton.setName("exit");

        // Add buttons to grid
        constraints.gridy = 1;
        panel.add(buttonPanel, constraints);

        // Configure the frame
        splashFrame.setContentPane(panel);
        splashFrame.setTitle("MySlither");
        splashFrame.setSize(230,230);
        splashFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        splashFrame.setVisible(true);
        splashFrame.setResizable(false);
    }

    /**
     * Processes button presses in the GUI.
     * 
     * @param event the event generated by the button press
     */
    public void actionPerformed(ActionEvent event) {
        JButton source = (JButton) event.getSource();
        String name = (String) source.getName();

        // start the game if start button is pressed
        if (name.equals("start")) {
            // launch the game and close this current frame
            new MySlitherJFrame().setVisible(true);
            splashFrame.dispose();
        }

        if (name.equals("help")) {
            // launch the help window
            new Help();
        }

        if (name.equals("exit")) {
            // exit
            System.exit(0);
        }


    }



}